# Generated by Django 2.1.4 on 2019-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190304_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
