# Generated by Django 2.1.4 on 2019-02-21 18:44

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup_ID', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner')),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.CharField(default=6.9214, max_length=200)),
                ('longitude', models.CharField(default=122.079, max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_to', models.DateField()),
                ('time_to', models.TimeField()),
                ('registration', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(default='Draft', max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member_speaker', models.ManyToManyField(to='user.Member')),
                ('member_sponsor', models.ManyToManyField(related_name='sponsored_events', to='user.Member')),
                ('member_volunteer', models.ManyToManyField(related_name='volunteered_events', to='user.Member')),
                ('speakers', models.ManyToManyField(blank=True, to='event.Speaker')),
                ('sponsors', models.ManyToManyField(blank=True, to='event.Sponsor')),
                ('volunteers', models.ManyToManyField(to='event.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=300)),
                ('member_image', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('yes_rsvp', models.IntegerField(default=0)),
                ('no_rsvp', models.IntegerField(default=0)),
                ('manual_count', models.IntegerField(default=0)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=120, null=True)),
                ('feedback', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event_statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventStatistics'),
        ),
    ]
