# Generated by Django 2.1.4 on 2019-02-21 18:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('become_a_sponsor_url', models.URLField(default='https://gdgzamboanga.herokuapp.com/', max_length=1000)),
                ('become_a_volunteer_url', models.URLField(default='https://gdgzamboanga.herokuapp.com/', max_length=1000)),
                ('speaker_request_url', models.URLField(default='https://gdgzamboanga.herokuapp.com/', max_length=1000)),
                ('media_kit_url', models.URLField(default='https://gdgzamboanga.herokuapp.com/', max_length=1000)),
                ('photo_gallery_url', models.URLField(default='https://gdgzamboanga.herokuapp.com/', max_length=1000)),
                ('about_us', models.TextField(default='GDG Zamboanga')),
                ('google_plus_link', models.URLField(default='https://plus.google.com/', max_length=300)),
                ('facebook_link', models.URLField(default='https://facebook.com/', max_length=300)),
                ('twitter_link', models.URLField(default='https://twitter.com', max_length=300)),
                ('youtube_link', models.URLField(default='https://youtube.com', max_length=300)),
                ('instagram_link', models.URLField(default='https://instagram.com', max_length=300)),
                ('meetup_link', models.URLField(default='https://meetup.com', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('expertise', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.BooleanField(default=True)),
                ('blogs', models.BooleanField(default=True)),
                ('stories', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Blog Creator', max_length=120)),
                ('activated', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
